import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createGuideServer } from './index.mjs';
import { validateEntry, trackStats } from './store.mjs';
const origin='http://127.0.0.1:19531';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lost-sierra-test-'));
let app,cookie='';
async function start(){app=await createGuideServer({dataDir:dir,origin});await new Promise(resolve=>app.server.listen(19531,'127.0.0.1',resolve));}
async function call(endpoint,method='GET',body,headers={}){const response=await fetch(origin+'/api/'+endpoint,{method,headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')};}
test('persistent guide and authenticated publishing',async t=>{
 await start();t.after(async()=>{await app.close();fs.rmSync(dir,{recursive:true,force:true});});
 const publicData=await call('catalog');
 assert.equal(publicData.status,200);
 const published=publicData.body.entries;
 assert.ok(published.some(e=>e.id==='beckwourth-peak'&&e.hasTrack));
 assert.ok(published.some(e=>e.kind==='adventure'));
 assert.ok(published.every(e=>e.status==='published'&&!['Nevada City','Truckee','Susanville'].includes(e.area)));
 assert.ok(!published.some(e=>['gold-valley-rim-pauley-creek-dh','cal-ida-trail'].includes(e.id)));
 const curated=JSON.parse(fs.readFileSync(new URL('../data/curated-rides.json',import.meta.url)));
 const scope=JSON.parse(fs.readFileSync(new URL('../data/guide-scope.json',import.meta.url)));
 for(const {id} of curated.filter(e=>!scope.excludedEntries.includes(e.id)&&(!e.entry?.status||e.entry.status==='published')))assert.ok(published.some(e=>e.id===id&&e.hasTrack),`Missing curated track: ${id}`);
 await t.test('public cannot edit or export',async()=>{assert.equal((await call('admin/entries')).status,401);assert.equal((await call('admin/entries/beckwourth-peak')).status,401);assert.equal((await call('admin/export')).status,401);assert.equal((await call('admin/entries/beckwourth-peak','PUT',{})).status,401);});
 await t.test('one-time setup requires secret and same origin',async()=>{assert.equal((await call('setup','POST',{username:'admin',password:'test-only-password',token:'wrong'})).status,403);assert.equal((await call('setup','POST',{username:'admin',password:'test-only-password',token:app.setupToken},{Origin:'https://other.example'})).status,403);const r=await call('setup','POST',{username:'admin',password:'test-only-password',token:app.setupToken});assert.equal(r.status,201);assert.match(r.cookie,/HttpOnly/);assert.match(r.cookie,/SameSite=Strict/);cookie=r.cookie.split(';')[0];assert.equal((await call('setup','POST',{})).status,409);assert.equal(fs.existsSync(path.join(dir,'setup-token')),false);});
 let ride=(await call('admin/entries')).body.entries.find(e=>e.id==='beckwourth-peak');
 await t.test('start and finish map links persist and a loop needs only one URL',async()=>{
   const buzz=(await call('catalog')).body.entries.find(e=>e.id==='buzzards-roost-ridge');
   assert.equal(buzz.startMapsUrl,'https://maps.app.goo.gl/dMWgUQ9zvk9EmSez5');assert.equal(buzz.sameStartFinish,true);assert.equal(buzz.finishMapsUrl,null);
   let saved=await call('admin/entries/'+ride.id,'PUT',{...ride,startMapsUrl:'https://maps.app.goo.gl/start',finishMapsUrl:'https://maps.app.goo.gl/finish',sameStartFinish:false});
   assert.equal(saved.status,200);ride=saved.body.entry;
   await app.close();await start();
   const published=(await call('catalog')).body.entries.find(e=>e.id===ride.id);
   assert.equal(published.startMapsUrl,ride.startMapsUrl);assert.equal(published.finishMapsUrl,ride.finishMapsUrl);assert.equal(published.sameStartFinish,false);
   saved=await call('admin/entries/'+ride.id,'PUT',{...ride,finishMapsUrl:'',sameStartFinish:true});
   assert.equal(saved.status,200);ride=saved.body.entry;assert.equal(ride.sameStartFinish,true);assert.equal(ride.finishMapsUrl,'');
 });
 await t.test('CMS exposes original source, track metadata and saved viewer settings',async()=>{
   let detail=await call('admin/entries/'+ride.id);
   assert.equal(detail.status,200);assert.equal(detail.body.original.id,ride.id);
   assert.equal(detail.body.source.id,'everstoke-planner');assert.ok(detail.body.track.pointCount>2);
   const viewer={home:{position:[-80,75,-140],target:[-5,0,-8],zoom:1.4},pointsOfInterest:[{name:'Park',latitude:39.80559,longitude:-120.46534,color:'#34877b',url:'https://example.com/park'}],angleBeats:[[0,-155],[1,170]],baseElevation:1350,scale:1,contextLabels:{mode:'only',names:['North Yuba River']}};
   const saved=await call('admin/entries/'+ride.id,'PUT',{...ride,viewer});assert.equal(saved.status,200);ride=saved.body.entry;
   detail=await call('admin/entries/'+ride.id);assert.deepEqual(detail.body.entry.viewer,viewer);
   assert.equal(detail.body.history[0].action,'entry-update');assert.deepEqual(detail.body.history[0].after.viewer,viewer);
   assert.equal((await call('admin/entries/not-a-ride')).status,404);
 });
 await t.test('public slugs rename without changing IDs, tracks, homes, or old links',async()=>{
   const stableId=ride.id,home=ride.viewer.home;
   const trackBefore=(await call('admin/entries/'+stableId)).body.track;
   let saved=await call('admin/entries/'+stableId,'PUT',{...ride,slug:'beckwourth-vista'});
   assert.equal(saved.status,200);ride=saved.body.entry;
   assert.equal(ride.id,stableId);assert.equal(ride.slug,'beckwourth-vista');assert.deepEqual(ride.viewer.home,home);
   let catalog=(await call('catalog')).body;
   assert.equal(catalog.slugAliases[stableId],stableId);assert.equal(catalog.slugAliases['beckwourth-vista'],stableId);
   assert.equal(catalog.slugAliases['mt-elwell'],'mt-elwell-hard-way');
   assert.equal((await call('tracks/'+stableId)).status,200);
   assert.deepEqual((await call('admin/entries/'+stableId)).body.track,trackBefore);
   saved=await call('admin/entries/'+stableId,'PUT',{...ride,slug:'beckwourth-panoramic'});
   assert.equal(saved.status,200);ride=saved.body.entry;
   catalog=(await call('catalog')).body;
   assert.equal(catalog.slugAliases['beckwourth-vista'],stableId);
   assert.equal(catalog.slugAliases['beckwourth-panoramic'],stableId);
   assert.equal((await call('admin/entries/'+stableId,'PUT',{...ride,slug:'haskell-peak'})).status,409);
   assert.equal((await call('admin/entries/'+stableId,'PUT',{...ride,slug:'mt-elwell'})).status,409);
   assert.equal((await call('admin/entries/'+stableId,'PUT',{...ride,slug:'Invalid Slug'})).status,400);
   assert.equal((await call('admin/entries/'+stableId,'PUT',{...ride,slug:['array-slug']})).status,400);
   let other=(await call('admin/entries')).body.entries.find(e=>e.id==='haskell-peak');
   saved=await call('admin/entries/'+other.id,'PUT',{...other,slug:'haskell-story'});assert.equal(saved.status,200);other=saved.body.entry;
   saved=await call('admin/entries/'+other.id,'PUT',{...other,slug:'haskell-journey'});assert.equal(saved.status,200);
   assert.equal((await call('admin/entries/'+stableId,'PUT',{...ride,slug:'haskell-story'})).status,409);
   const collidingNew={id:'haskell-story',kind:'ride',name:'Collision',area:'Portola',status:'draft',coordinates:{lat:39.8,lng:-120.45}};
   assert.equal((await call('admin/entries/haskell-story','PUT',collidingNew)).status,409);
   assert.equal((await call('admin/entries/'+stableId)).body.history.filter(h=>h.action==='entry-update').length>=2,true);
   await app.close();await start();
   ride=(await call('admin/entries')).body.entries.find(e=>e.id===stableId);
   catalog=(await call('catalog')).body;
   assert.equal(ride.slug,'beckwourth-panoramic');assert.equal(catalog.slugAliases['beckwourth-vista'],stableId);
   assert.equal(catalog.slugAliases['haskell-story'],'haskell-peak');
 });
 await t.test('drafts and tracks stay private; conflicts preserve newer edits',async()=>{const updated=await call('admin/entries/'+ride.id,'PUT',{...ride,status:'draft',notes:'Test draft'});assert.equal(updated.status,200);assert.equal((await call('admin/entries/'+ride.id,'PUT',ride)).status,409);ride=updated.body.entry;const saved=cookie;cookie='';const catalog=(await call('catalog')).body;assert.ok(!catalog.entries.some(e=>e.id===ride.id));assert.equal(catalog.slugAliases[ride.id],undefined);assert.equal(catalog.slugAliases['beckwourth-vista'],undefined);assert.equal((await call('tracks/'+ride.id)).status,404);cookie=saved;assert.equal((await call('tracks/'+ride.id)).status,200);});
 await t.test('database survives restart without reseeding changes',async()=>{await app.close();await start();const entries=(await call('admin/entries')).body.entries;const saved=entries.find(e=>e.id===ride.id);assert.equal(saved.notes,'Test draft');assert.equal(saved.status,'draft');assert.equal((await call('session')).body.user.username,'admin');});
 await t.test('publish and track upload persist with provenance',async()=>{let r=await call('admin/entries/'+ride.id,'PUT',{...ride,status:'published'});ride=r.body.entry;assert.equal(r.status,200);r=await call('admin/entries/'+ride.id+'/track','PUT',{version:ride.version,feature:{type:'LineString',coordinates:[[-120.45,39.78,1500],[-120.449,39.781,1510]]},sourceLabel:'Test track',sourceUrl:'https://example.com/track'});assert.equal(r.status,200);assert.equal((await call('tracks/'+ride.id)).body.properties.sourceLabel,'Test track');assert.ok((await call('catalog')).body.entries.some(e=>e.id===ride.id));});
 await t.test('new entries, archive, and export omit credentials',async()=>{const r=await call('admin/entries/test-adventure','PUT',{id:'test-adventure',kind:'adventure',name:'Test','area':'Portola',coordinates:{lat:39.8,lng:-120.45},status:'draft'});assert.equal(r.status,201);assert.equal((await call('admin/entries/test-adventure','PUT',{...r.body.entry,status:'archived'})).status,200);const exported=await call('admin/export');assert.equal(exported.status,200);const current=(await call('admin/entries')).body.entries;assert.deepEqual(exported.body.entries.map(e=>e.id).sort(),current.map(e=>e.id).sort());assert.equal(exported.body.entries.find(e=>e.id==='test-adventure').status,'archived');assert.ok(!JSON.stringify(exported.body).includes('password_hash'));});
 await t.test('cross-origin writes rejected even with a session',async()=>{assert.equal((await call('admin/entries/'+ride.id,'PUT',ride,{Origin:'https://other.example'})).status,403);});
 await t.test('logout revokes the session and login requires the password',async()=>{assert.equal((await call('logout','POST',{})).status,200);assert.equal((await call('admin/entries')).status,401);assert.equal((await call('login','POST',{username:'admin',password:'wrong'})).status,401);const r=await call('login','POST',{username:'admin',password:'test-only-password'});assert.equal(r.status,200);cookie=r.cookie.split(';')[0];assert.equal((await call('admin/entries')).status,200);});
});
test('data validation rejects unsafe URLs and malformed or out-of-region tracks',()=>{
 const entry={id:'test',kind:'ride',name:'Test',area:'Portola',status:'draft',coordinates:{lat:39.8,lng:-120.45}};
 assert.throws(()=>validateEntry({...entry,routeUrl:'javascript:alert(1)'}));
 assert.throws(()=>validateEntry({...entry,startMapsUrl:'javascript:alert(1)'}));
 assert.throws(()=>validateEntry({...entry,finishMapsUrl:'data:text/html,unsafe'}));
 assert.throws(()=>validateEntry({...entry,sameStartFinish:'true'}));
 assert.throws(()=>validateEntry({...entry,coordinates:{lat:null,lng:-120.45}}));
 assert.throws(()=>trackStats({type:'LineString',coordinates:[[-120,38],[-120,39]]}));
 assert.throws(()=>trackStats({type:'LineString',coordinates:[[-120.4,39.8],[-120.5,40.1]]}));
 assert.throws(()=>trackStats({type:'LineString',coordinates:[[-120.4,39.8,NaN],[-120.401,39.801]]}));
 const stats=trackStats({type:'LineString',coordinates:[[-120.45,39.8],[-120.449,39.801]]});assert.ok(stats.distance>100);assert.equal(stats.ascent,null);
});
